pipeline:
  identifier: Build_nofarb_repo1_1710527901262
  name: Build repo1
  orgIdentifier: default
  projectIdentifier: NofarUri
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.github
        repoName: nofarb/repo1
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    shell: Sh
                    command: echo hello world <+pipeline.variables.var1>
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
  variables:
    - name: var1
      type: String
      description: ""
      required: true
      value: <+input>
